.PHONY: all-bin srv clnt relay

all-bin: srv clnt relay

srv: Makefile.server
	@make -sf Makefile.server

clnt: Makefile.client
	@make -sf Makefile.client

relay: Makefile.relay
	@make -sf Makefile.relay

